#!/usr/bin/make -f
#
#	Copyright (C) 2003-2008 Jari Aalto
#	Copyright (C) YYYY Firstname Lastname
#
#	This program is free software; you can redistribute it and/or
#	modify it under the terms of the GNU General Public License as
#	published by the Free Software Foundation; either version 2 of the
#	License, or (at your option) any later version
#
#	This program is distributed in the hope that it will be useful, but
#	WITHOUT ANY WARRANTY; without even the implied warranty of
#	MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
#	General Public License for more details.
#
#	Visit <http://www.gnu.org/copyleft/gpl.html>

ifneq (,)
This makefile requires GNU Make.
endif

DESTDIR		=
prefix		= /usr
exec_prefix	= $(prefix)
man_prefix	= $(prefix)/share

PACKAGE		= foo
INSTALL		= /usr/bin/install
INSTALL_BIN	= $(INSTALL) -m 755
INSTALL_SUID	= $(INSTALL) -m 4755
INSTALL_DATA	= $(INSTALL) -m 644

INSTALL_OBJS_BIN   = $(PACKAGE)
INSTALL_OBJS_MAN1  = *.1 *.1x
INSTALL_OBJS_SHARE =

MANDIR1		= $(DESTDIR)$(man_prefix)/man/man1
MANDIR5		= $(DESTDIR)$(man_prefix)/man/man5
MANDIR8		= $(DESTDIR)$(man_prefix)/man/man8
BINDIR		= $(DESTDIR)$(exec_prefix)/bin
SBINDIR		= $(DESTDIR)$(exec_prefix)/sbin
ETCDIR		= $(DESTDIR)/etc/$(PACKAGE)
SHAREDIR	= $(DESTDIR)$(prefix)/share/$(PACKAGE)
LIBDIR		= $(DESTDIR)$(prefix)/lib/$(PACKAGE)
DOCDIR		= $(DESTDIR)$(prefix)/share/doc

DEBUG		= -g
CC		= gcc
GCCFLAGS	= -Wall
CFLAGS		= $(GCCFLAGS) $(DEBUG) -O2
LDFLAGS		=

SRCS		= $(PACKAGE).c
OBJS		= $(SRCS:.c=.o)
EXE		= $(PACKAGE)

ASM_SRCS	=
ASM_OBJS	= $(ASM_SRCS:.asm=.o)
ASM_FLAGS	=

.PHONY: clean distclean install install-man install-bin
.SUFFIXES: .asm

all: $(PACKAGE)

$(EXE): $(OBJS)
	$(CC) $(CFLAGS) -o $@ $(OBJS) $(LDFLAGS)

.asm.o: $(ASM_OBJS)
	nasm $(ASM_FLAGS) $<

clean:
	# clean
	-rm -f *[#~] *.\#* *.o *.exe core *.stackdump $(PACKAGE) *.exe

distclean: clean

install-etc:
	# install-etc
	$(INSTALL_BIN) -d $(ETCDIR)
	$(INSTALL_BIN)	  $(INSTALL_OBJS_ETC) $(ETCDIR)

install-bin:
	# install-bin
	$(INSTALL_BIN) -d $(BINDIR)
	$(INSTALL_BIN) -s $(INSTALL_OBJS_BIN) $(BINDIR)

install-man:
	# install-man
	$(INSTALL_BIN) -d $(MANDIR1)
	$(INSTALL_DATA) $(INSTALL_OBJS_MAN1) $(MANDIR1)

install: all install-bin install-man

# End of file
